/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Footer.module.css";

const ContactInfo: React.FC = () => {
  return (
    <div className={styles.contactInfo}>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/d8292ef9203972eedf9c4f40353b53fa48b910f8f2e3ba56d4721ea5baf5b69f?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
        className={styles.logo}
        alt="Company logo"
      />
      <div className={styles.email}>hello@playstationplus.store</div>
      <div className={styles.workingHours}>
        принимаем заявки с 11:00 до 21:00 (МСК)
      </div>
      <div className={styles.socialIcons}>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/9e6026c93497c05916de173ea3de67c0fbb215f5f28189918e1ffec1b564ccd3?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          className={styles.socialIcon}
          alt="Social media icon"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/82bc375cf21f23dd196b5eb4ba10e90b3c643e0a58d181eacd952cd07d571335?placeholderIfAbsent=true&apiKey=f19410a7ed964887a882a08cb3ad097c"
          className={styles.socialIcon}
          alt="Social media icon"
        />
      </div>
    </div>
  );
};

export default ContactInfo;
