/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Footer.module.css";

interface NavigationColumnProps {
  title: string;
  items: string[];
}

const NavigationColumn: React.FC<NavigationColumnProps> = ({
  title,
  items,
}) => {
  return (
    <div className={styles.navColumn}>
      <div className={styles.navList}>
        <h2 className={styles.navTitle}>{title}</h2>
        <ul className={styles.navItems}>
          {items.map((item, index) => (
            <li key={index} className={styles.navItem}>
              <a href="#" className={styles.navLink}>
                {item}
              </a>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
};

export default NavigationColumn;
