/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Footer.module.css";

interface PaymentIconProps {
  src: string;
  width: string;
}

const PaymentIcon: React.FC<PaymentIconProps> = ({ src, width }) => {
  return (
    <img
      loading="lazy"
      src={src}
      className={styles.paymentIcon}
      style={{ width }}
      alt="Payment method icon"
    />
  );
};

export default PaymentIcon;
